### ISSUE TITLE
Commentary links to go to the proper page.

### ISSUE THREAD

**Issue by Khematto** [bksubhuti/tipitaka-pali-reader#138] opened 2023-01-25 04:43 UTC
First of all, anumodana for all the great work. It's already a great app.

One slight inconvenience is that in long sections, there is no link to the relevant passage in the Commentary from pages after the page on which the section begins. 

A solution would be to have the default action be to search for the last link on the nearest previous page containing a link and present that as the option.

It would save a little time flipping back each time.

**Comment by bksubhuti** [comment] 2023-09-03 11:26
Currently, we have only page numbers for our data.
It might be possible later.  However, this is how it is for now.
Will rename title and keep open.

**Comment by bksubhuti** [comment] 2023-09-03 11:28
actually with some thought.  It is really something we cannot do for the near future.
The linked books are based on myanmar paragraph numbers. 
We have improved the MAT buttons, but I'm going to close this issue.
![Uploading image.png…]()

**Closed by bksubhuti** 2023-09-03 11:28 UTC
Labels: enhancement

**Comment by Khematto** [comment] 2023-12-06 00:26
Dear Ven. Subhuti,
Some of my Thai monk friends are interested in the Buddhist Sun app.
What would you need for a Thai version? I could translate whatever
vocabulary you need, if you are interested.

**Comment by bksubhuti** [comment] 2023-12-06 03:32
This issue has been moved..  https://github.com/bksubhuti/buddhist_sun/issues/5
The issue is ready for translation .
Please continue there.
